services:
  - type: web
    name: inoutburgermenu
    env: ruby
    plan: free
    buildCommand: bundle install && yarn install && bundle exec rake assets:precompile
    startCommand: bundle exec rails server -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
